/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.lsc.sde.analytics.workspace.management.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-20T11:03:36.264Z[Etc/UTC]")
public class V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple {
  public static final String SERIALIZED_NAME_SECRET_NAME = "secretName";
  @SerializedName(SERIALIZED_NAME_SECRET_NAME)
  private String secretName;


  public V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple secretName(String secretName) {
    
    this.secretName = secretName;
    return this;
  }

   /**
   * Name of the secret that contains the oauth2 token related to this datasource
   * @return secretName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the secret that contains the oauth2 token related to this datasource")

  public String getSecretName() {
    return secretName;
  }


  public void setSecretName(String secretName) {
    this.secretName = secretName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple v1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple = (V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple) o;
    return Objects.equals(this.secretName, v1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple.secretName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secretName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple {\n");
    sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

