/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.lsc.sde.analytics.workspace.management.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.lsc.sde.analytics.workspace.management.models.V1AnalyticsCrateSpecRepo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1AnalyticsCrateSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-03T09:52:21.861Z[Etc/UTC]")
public class V1AnalyticsCrateSpec {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_REPO = "repo";
  @SerializedName(SERIALIZED_NAME_REPO)
  private V1AnalyticsCrateSpecRepo repo;


  public V1AnalyticsCrateSpec description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * REQUIRED. A simple description which can be multiple lines describing the workspace
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "REQUIRED. A simple description which can be multiple lines describing the workspace")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public V1AnalyticsCrateSpec displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * REQUIRED. The short display name used as the title for the workspace.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "REQUIRED. The short display name used as the title for the workspace.")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public V1AnalyticsCrateSpec path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * The path to the file in the repository which contains the ro-crates metadata.
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The path to the file in the repository which contains the ro-crates metadata.")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public V1AnalyticsCrateSpec repo(V1AnalyticsCrateSpecRepo repo) {
    
    this.repo = repo;
    return this;
  }

   /**
   * Get repo
   * @return repo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1AnalyticsCrateSpecRepo getRepo() {
    return repo;
  }


  public void setRepo(V1AnalyticsCrateSpecRepo repo) {
    this.repo = repo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AnalyticsCrateSpec v1AnalyticsCrateSpec = (V1AnalyticsCrateSpec) o;
    return Objects.equals(this.description, v1AnalyticsCrateSpec.description) &&
        Objects.equals(this.displayName, v1AnalyticsCrateSpec.displayName) &&
        Objects.equals(this.path, v1AnalyticsCrateSpec.path) &&
        Objects.equals(this.repo, v1AnalyticsCrateSpec.repo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, displayName, path, repo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AnalyticsCrateSpec {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

