/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.lsc.sde.analytics.workspace.management.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.lsc.sde.analytics.workspace.management.models.V1AnalyticsDataSourceSpecDatabricksConnectionOauth2Token;
import io.github.lsc.sde.analytics.workspace.management.models.V1AnalyticsDataSourceSpecDatabricksConnectionPersonalAccessToken;
import io.github.lsc.sde.analytics.workspace.management.models.V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1AnalyticsDataSourceSpecDatabricksConnection
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-20T11:03:36.264Z[Etc/UTC]")
public class V1AnalyticsDataSourceSpecDatabricksConnection {
  public static final String SERIALIZED_NAME_HOST_NAME = "hostName";
  @SerializedName(SERIALIZED_NAME_HOST_NAME)
  private String hostName;

  public static final String SERIALIZED_NAME_HTTP_PATH = "httpPath";
  @SerializedName(SERIALIZED_NAME_HTTP_PATH)
  private String httpPath;

  public static final String SERIALIZED_NAME_OAUTH2_TOKEN = "oauth2Token";
  @SerializedName(SERIALIZED_NAME_OAUTH2_TOKEN)
  private V1AnalyticsDataSourceSpecDatabricksConnectionOauth2Token oauth2Token;

  public static final String SERIALIZED_NAME_PERSONAL_ACCESS_TOKEN = "personalAccessToken";
  @SerializedName(SERIALIZED_NAME_PERSONAL_ACCESS_TOKEN)
  private V1AnalyticsDataSourceSpecDatabricksConnectionPersonalAccessToken personalAccessToken;

  public static final String SERIALIZED_NAME_SERVICE_PRINCIPLE = "servicePrinciple";
  @SerializedName(SERIALIZED_NAME_SERVICE_PRINCIPLE)
  private V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple servicePrinciple;


  public V1AnalyticsDataSourceSpecDatabricksConnection hostName(String hostName) {
    
    this.hostName = hostName;
    return this;
  }

   /**
   * The hostname of the databricks instance
   * @return hostName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The hostname of the databricks instance")

  public String getHostName() {
    return hostName;
  }


  public void setHostName(String hostName) {
    this.hostName = hostName;
  }


  public V1AnalyticsDataSourceSpecDatabricksConnection httpPath(String httpPath) {
    
    this.httpPath = httpPath;
    return this;
  }

   /**
   * The path of the databricks instance
   * @return httpPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The path of the databricks instance")

  public String getHttpPath() {
    return httpPath;
  }


  public void setHttpPath(String httpPath) {
    this.httpPath = httpPath;
  }


  public V1AnalyticsDataSourceSpecDatabricksConnection oauth2Token(V1AnalyticsDataSourceSpecDatabricksConnectionOauth2Token oauth2Token) {
    
    this.oauth2Token = oauth2Token;
    return this;
  }

   /**
   * Get oauth2Token
   * @return oauth2Token
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1AnalyticsDataSourceSpecDatabricksConnectionOauth2Token getOauth2Token() {
    return oauth2Token;
  }


  public void setOauth2Token(V1AnalyticsDataSourceSpecDatabricksConnectionOauth2Token oauth2Token) {
    this.oauth2Token = oauth2Token;
  }


  public V1AnalyticsDataSourceSpecDatabricksConnection personalAccessToken(V1AnalyticsDataSourceSpecDatabricksConnectionPersonalAccessToken personalAccessToken) {
    
    this.personalAccessToken = personalAccessToken;
    return this;
  }

   /**
   * Get personalAccessToken
   * @return personalAccessToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1AnalyticsDataSourceSpecDatabricksConnectionPersonalAccessToken getPersonalAccessToken() {
    return personalAccessToken;
  }


  public void setPersonalAccessToken(V1AnalyticsDataSourceSpecDatabricksConnectionPersonalAccessToken personalAccessToken) {
    this.personalAccessToken = personalAccessToken;
  }


  public V1AnalyticsDataSourceSpecDatabricksConnection servicePrinciple(V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple servicePrinciple) {
    
    this.servicePrinciple = servicePrinciple;
    return this;
  }

   /**
   * Get servicePrinciple
   * @return servicePrinciple
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple getServicePrinciple() {
    return servicePrinciple;
  }


  public void setServicePrinciple(V1AnalyticsDataSourceSpecDatabricksConnectionServicePrinciple servicePrinciple) {
    this.servicePrinciple = servicePrinciple;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AnalyticsDataSourceSpecDatabricksConnection v1AnalyticsDataSourceSpecDatabricksConnection = (V1AnalyticsDataSourceSpecDatabricksConnection) o;
    return Objects.equals(this.hostName, v1AnalyticsDataSourceSpecDatabricksConnection.hostName) &&
        Objects.equals(this.httpPath, v1AnalyticsDataSourceSpecDatabricksConnection.httpPath) &&
        Objects.equals(this.oauth2Token, v1AnalyticsDataSourceSpecDatabricksConnection.oauth2Token) &&
        Objects.equals(this.personalAccessToken, v1AnalyticsDataSourceSpecDatabricksConnection.personalAccessToken) &&
        Objects.equals(this.servicePrinciple, v1AnalyticsDataSourceSpecDatabricksConnection.servicePrinciple);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostName, httpPath, oauth2Token, personalAccessToken, servicePrinciple);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AnalyticsDataSourceSpecDatabricksConnection {\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    httpPath: ").append(toIndentedString(httpPath)).append("\n");
    sb.append("    oauth2Token: ").append(toIndentedString(oauth2Token)).append("\n");
    sb.append("    personalAccessToken: ").append(toIndentedString(personalAccessToken)).append("\n");
    sb.append("    servicePrinciple: ").append(toIndentedString(servicePrinciple)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

