/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.lsc.sde.analytics.workspace.management.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * V1AnalyticsDataSourceBindingSpecApprovals
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-20T11:03:36.264Z[Etc/UTC]")
public class V1AnalyticsDataSourceBindingSpecApprovals {
  public static final String SERIALIZED_NAME_APPROVAL_GIVEN = "approvalGiven";
  @SerializedName(SERIALIZED_NAME_APPROVAL_GIVEN)
  private OffsetDateTime approvalGiven;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_JOB_TITLE = "jobTitle";
  @SerializedName(SERIALIZED_NAME_JOB_TITLE)
  private String jobTitle;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public V1AnalyticsDataSourceBindingSpecApprovals approvalGiven(OffsetDateTime approvalGiven) {
    
    this.approvalGiven = approvalGiven;
    return this;
  }

   /**
   * The time at which approval was given by the user
   * @return approvalGiven
  **/
  @ApiModelProperty(required = true, value = "The time at which approval was given by the user")

  public OffsetDateTime getApprovalGiven() {
    return approvalGiven;
  }


  public void setApprovalGiven(OffsetDateTime approvalGiven) {
    this.approvalGiven = approvalGiven;
  }


  public V1AnalyticsDataSourceBindingSpecApprovals email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * The email address of the approver
   * @return email
  **/
  @ApiModelProperty(required = true, value = "The email address of the approver")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public V1AnalyticsDataSourceBindingSpecApprovals jobTitle(String jobTitle) {
    
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * The job title of the approver
   * @return jobTitle
  **/
  @ApiModelProperty(required = true, value = "The job title of the approver")

  public String getJobTitle() {
    return jobTitle;
  }


  public void setJobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
  }


  public V1AnalyticsDataSourceBindingSpecApprovals name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the approver
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name of the approver")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1AnalyticsDataSourceBindingSpecApprovals type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of approval being given
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of approval being given")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AnalyticsDataSourceBindingSpecApprovals v1AnalyticsDataSourceBindingSpecApprovals = (V1AnalyticsDataSourceBindingSpecApprovals) o;
    return Objects.equals(this.approvalGiven, v1AnalyticsDataSourceBindingSpecApprovals.approvalGiven) &&
        Objects.equals(this.email, v1AnalyticsDataSourceBindingSpecApprovals.email) &&
        Objects.equals(this.jobTitle, v1AnalyticsDataSourceBindingSpecApprovals.jobTitle) &&
        Objects.equals(this.name, v1AnalyticsDataSourceBindingSpecApprovals.name) &&
        Objects.equals(this.type, v1AnalyticsDataSourceBindingSpecApprovals.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approvalGiven, email, jobTitle, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AnalyticsDataSourceBindingSpecApprovals {\n");
    sb.append("    approvalGiven: ").append(toIndentedString(approvalGiven)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    jobTitle: ").append(toIndentedString(jobTitle)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

